# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'PhotoBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FacebookCore'
  pod 'FacebookLogin'

  # Pods for PhotoBrowser

  target 'PhotoBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoBrowserUITests' do
    # Pods for testing
  end

end
